### ISSUE TITLE
Vertaisarviointi 1

### ISSUE THREAD

**Issue by pllk** [taapp/tsoha-keskustelusovellus#1]
Käyttökokemus:

* Pystyin luomaan tunnuksen ja kirjautumaan sisään. Yritin myös lähettää viestejä keskusteluun, mutta se tuntui sekavalta tällä hetkellä enkä tiedä mitä tapahtui.

* Sovelluksen käyttöliittymää kannattaa parantaa niin, että käyttäjä ymmärtää paremmin, millä sivulla ollaan ja miten toiminnot vaikuttavat.

Tekninen toteutus:

* Tekninen toteutus on hyvä ja koodia on helppoa lukea.

* Koodissa käytetään sekaisin merkkejä `'` ja `"` merkkijonojen kanssa. Kannattaa valita toinen näistä tavoista ja käyttää sitä yhdenmukaisesti.

* Koodissa on melko paljon debug-printtauksia. Muista poistaa nämä, kun niille ei ole enää tarvetta.

* Koodin muuttujien nimiä voi vielä parantaa. Esimerkiksi nimi `ls` ei ole hyvä, koska koodin lukijan on vaikea tietää, mitä se tarkoittaa.

* SQL-skeemassa näyttäisi paremmalta, että taulujen välissä on yksi tyhjä rivi.

**Comment by taapp** [comment]
Kiitos paljon palautteesta.
