### ISSUE TITLE
Peer review

### ISSUE THREAD

**Issue by ni-eminen** [taapp/tsoha-keskustelusovellus#2]
Observations:

1. Navbar would be handy, as there is no easy way to navigate over the pages currently
2. Writing a new message throws the user back to the /areas page, instead of refreshing the thread
3. Some bootstrap styling would be a nice addition
4. Schema looks good, no extra.
5. Some sizeable sql queries such as the ones in areas.py could possibly be simplified quite a bit
6. Search function could be made more intuitive by launching the search via enter (instead of a newline) and adding a back button to  the search_messages page.

**Comment by taapp** [comment]
Thank you for the comments
